# Deployment file 
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: i27-product-stage
#  namespace: cart-stage-ns
spec:
  replicas: 1
  selector:
    matchLabels:
        app: i27-product-stage
  template:
    metadata:
      labels:
        app: i27-product-stage
    spec:
      imagePullSecrets: 
      - name: docker-secret  #same name you created "docker-registry secret" under stage namespace
      containers:
      - name: i27-product-stage
        image: DIT # this image along with tag will be replaced dynamically from shared lib
--- 
apiVersion: v1
kind: Service 
metadata:
  name: i27-product-stage
  labels:
    app: i27-product-stage
spec:
  type: NodePort
  ports:
  - port: 80 # this is port on which service is running
    targetPort: 8132 # port where container is running
  selector:
    app: i27-product-stage