# Creating a deployment file for dev environment
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: i27-product-dev
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: i27-product-dev
  template:
    metadata:
      labels:
        app: i27-product-dev
    spec:
      containers:
        - name: i27-product-dev
          image: DIT   # "DIT" your own name, which will later replacez with shared libraries
---
# Service 
apiVersion: v1
kind: Service
metadata: 
  name: i27-product-dev-svc
spec:  
  selector: 
    app: i27-product-dev #this name matches with the above matadata->labelname, otherwise it won't create the endpoint
  ports:
    - protocol: TCP
      port: 80    # This is service port, any port you need
      targetPort: 8761  # Same as your application port
  type: NodePort
    
